import React, {Component} from 'react';
import './Terms.css';

export default class EULA extends Component {
    render() {
        return (
            <div className='scrollable'>
             <p>


             End User License Agreement

             LAST UPDATED: MARCH 11TH, 2017

             PLEASE CAREFULLY READ THESE TERMS AND CONDITIONS (THESE "TERMS") BEFORE USING THE DEEP IDOL PLATFORM (AS DEFINED BELOW). THESE TERMS FORM A BINDING AND EXECUTED WRITTEN AGREEMENT (THE "AGREEMENT") BETWEEN DEEP IDOL, INC., A DELAWARE CORPORATION ("DEEP IDOL") AND THE ENTITY AGREEING TO THE LICENSE AGREEMENT ("USER"). THIS AGREEMENT IS EFFECTIVE AS OF THE DATE YOU CLICK THE "ACCEPT" BUTTON BELOW (OR ANY SIMILAR BUTTON OR LINK AS MAY BE DESIGNATED BY DEEP IDOL TO SHOW YOUR ACCEPTANCE OF THESE TERMS) (SUCH DATE, THE "EFFECTIVE DATE"). IF YOU ARE ACCEPTING ON BEHALF OF YOUR EMPLOYER OR ANOTHER ENTITY, YOU REPRESENT AND WARRANT THAT: (I) YOU HAVE FULL LEGAL AUTHORITY TO BIND YOUR EMPLOYER, OR THE APPLICABLE ENTITY, TO THE AGREEMENT; (II) YOU HAVE READ AND UNDERSTAND THIS AGREEMENT; AND (III) YOU AGREE, ON BEHALF OF THE PARTY THAT YOU REPRESENT, TO THIS AGREEMENT. ACCEPTANCE OF THIS LICENSE AGREEMENT IS REQUIRED AS A CONDITION TO PROCEEDING WITH THE DOWNLOAD, INSTALLATION, AND/OR USE OF THE DEEP IDOL PLATFORM (AS DEFINED BELOW). IF YOU DO NOT AGREE TO ALL OF THE TERMS AND CONDITIONS OF THE AGREEMENT OR IF YOU DO NOT HAVE THE LEGAL AUTHORITY TO BIND YOUR EMPLOYER OR THE APPLICABLE ENTITY, CLICK THE "DO NOT ACCEPT" BUTTON BELOW AND DO NOT USE THE DEEP IDOL PLATFORM.

             USER AND DEEP IDOL MAY EACH BE REFERRED TO HEREIN AS A "PARTY" IN THESE TERMS, AND ARE, COLLECTIVELY, THE "PARTIES".

             DEEP IDOL MAY CHANGE THESE TERMS AND CONDITIONS UPON THIRTY (30) DAYS' WRITTEN NOTICE TO USER, WHICH DEEP IDOL MAY DELIVER BY EMAIL OR BY POSTING NOTICE OF THE CHANGE ON DEEP IDOL'S WEBSITE LOCATED AT WWW.DEEP IDOL.COM. IF YOU CONTINUE TO USE THE DEEP IDOL PLATFORM AFTER THE EXPIRATION OF THE THIRTY (30) DAY NOTICE PERIOD, USER SHALL BE DEEMED TO HAVE ACCEPTED AND IS BOUND BY THE NEW TERMS.

             IN CONSIDERATION OF THE MUTUAL PROMISES BELOW AND OTHER GOOD AND VALUABLE CONSIDERATION THE SUFFICIENCY OF WHICH ARE HEREBY ACKNOWLEDGED, THE PARTIES AGREE AS FOLLOWS:

             BACKGROUND

             Deep Idol offers a self-service professional quality music creation platform. User wishes to access, and Deep Idol is willing to provide User access to use, the Deep Idol Platform (as defined below) on the terms and conditions described in this Agreement.

             1. DEFINITIONS

             The following terms, when used in this Agreement, shall have the following meanings:

             "Deep Idol Platform" means Deep Idol's self-service professional quality music creation platform (in object form only), which Deep Idol makes available to User as a service over the Internet.

             "Confidential Information" means, subject to the exceptions set forth in the following sentence, any information or data, regardless of whether it is in tangible form, disclosed by either Party (the "Disclosing Party") that the Disclosing Party has either marked as confidential or proprietary, or has identified in writing as confidential or proprietary within thirty (30) days of disclosure to the other Party (the "Receiving Party"); provided, however, that a Disclosing Party's business plans, strategies, technology, research and development, current and prospective customers, billing records, and products or services shall be deemed Confidential Information of the Disclosing Party even if not so marked or identified. Information will not be deemed "Confidential Information" if such information: (a) is known to the Receiving Party prior to receipt from the Disclosing Party directly or indirectly from a source other than one having an obligation of confidentiality to the Disclosing Party; (b) becomes known (independently of disclosure by the Disclosing Party) to the Receiving Party directly or indirectly from a source other than one having an obligation of confidentiality to the Disclosing Party; (c) becomes publicly known or otherwise ceases to be secret or confidential, except through a breach of this Agreement by the Receiving Party; or (d) is independently developed by the Receiving Party.

             "User Created Content" means any musical work, musical compositions, lyrics, sound recordings or other content created or developed by or on behalf of User to Deep Idol using the Deep Idol Platform.

             2. ACCESS TO DEEP IDOL PLATFORM; LICENSES

             2.1 Access to Deep Idol Platform. Subject to the terms and conditions of this Agreement, Deep Idol hereby grants User a non-exclusive right to access and use the Deep Idol Platform for its internal business purposes. User shall not license, sublicense, sell, resell, lease, transfer, distribute, time share, or otherwise commercially exploit or make the Deep Idol Platform available to any third party or reverse-engineer, decompile, translate, or create derivative works of the Deep Idol Platform in any manner. All ownership rights, title, and interest in and to the Deep Idol Platform, as such may be modified, upgraded, and/or enhanced from time to time (together with all intellectual property rights therein) will remain with and belong exclusively to Deep Idol. Deep Idol reserves all right, title, and interest in and to the Deep Idol Platform not expressly granted to User herein.

             2.2 Restrictions. Except as expressly permitted hereunder, User shall not and shall not permit or authorize any third party to: (a) copy, modify, reverse engineer, decompile, disassemble, or otherwise attempt to discover the source code, object code or underlying structure, ideas, or algorithms of any of the Deep Idol Platform; (b) translate or create derivative works based on any of the Deep Idol Platform; (c) license, sublicense, sell, resell, rent, lease, transfer, assign, distribute, time share, or otherwise commercially exploit or make the Deep Idol Platform available to any third party; (d) access or use the Deep Idol Platform (or any part thereof) or any User Created Content to create, develop, or build a product, solution, platform, or service which is the same as, substantially similar to or competes with the Deep Idol Platform; (e) use the Deep Idol Platform other than for its legitimate business purposes as contemplated by this Agreement; or (f) interfere with or disrupt the integrity or performance of the Deep Idol Platform or the data contained therein or attempt to gain unauthorized access to the Deep Idol Platform or its related systems or networks.

             2.3 Data. Deep Idol may: (i) copy, use, modify, distribute, display, and disclose User Data solely to the extent necessary to provide the Deep Idol Platform to User pursuant to the terms and conditions of this Agreement; (ii) copy, modify, and use User Data in connection with internal operations and functions, including, but not limited to, operational analytics and reporting, internal financial reporting and analysis, audit functions and archival purposes; and (iii) copy, modify and use User Data on an aggregate and de-identified basis, stripped of any personally identifiable information, for marketing purposes and internal business purposes and analytics, provided that such use or disclosure does not identify User or User's products, services, segments, attributes, search criteria, or any end user or consist of data solely attributable to User. For purposes hereof, "User Data" means any and all information collected and/or stored by or on behalf of Company in connection with or derived from User's use of the Deep Idol Platform, excluding data and information relating to the operation and/or performance of the Deep Idol Platform.

             2.4 Feedback. User may from time to time provide suggestions, comments for enhancements or functionality or other feedback ("Feedback") to Deep Idol with respect to the Deep Idol Platform. Deep Idol shall have full discretion to determine whether or not to proceed with the development of the requested enhancements, new features, or functionality. User hereby grants Deep Idol a royalty-free, fully paid up, worldwide, transferable, sublicensable, irrevocable, perpetual license to (a) copy, distribute, transmit, display, perform, and create derivative works of the Feedback; and (b) use the Feedback and/or any subject matter thereof, including without limitation, the right to develop, manufacture, have manufactured, market, promote, sell, have sold, offer for sale, have offered for sale, import, have imported, rent, provide, and/or lease products or services which practice or embody or are configured for use in practicing, the Feedback and/or any subject matter of the Feedback.

             3. FEES; REIMBURSEMENT OF EXPENSES

             3.1 Payment. User shall pay to Deep Idol the standard fees made publicly available on Deep Idol's website, www.AmperMusic.com. If payment of any fees is not made after it becomes due and payable, a late fee shall accrue at the rate of the lesser of one and one half percent (1.5%) per month or the highest legal rate permitted by law.

             3.2 Net of Taxes. All amounts payable by User to Deep Idol are exclusive of any sales, use and other taxes or duties, however designated, including without limitation, withholding taxes, royalties, know how payments, customs, privilege, excise, sales, use, value added, and property taxes (collectively "Taxes"). User shall be solely responsible for payment of any Taxes, except for those taxes based on the income of Deep Idol. User will not withhold any Taxes from any amounts due Deep Idol.

             4. OWNERSHIP AND CONFIDENTIALITY

             4.1 User Ownership Rights. Subject to the terms and conditions of this Agreement, Deep Idol hereby grants User the non-exclusive, royalty-free, personal, and non-commercial license and right to copy, display, distribute, modify (including the right to create derivative works of) and otherwise use the User Created Content.

             4.2 Deep Idol Ownership Rights. Except for the licenses and rights granted hereunder, all rights, title, and interests, including, but not limited to, all worldwide patent, copyright, trademark, trade secret, and any other rights in and to the Deep Idol Platform and any other Deep Idol product or service are retained by Deep Idol. User agrees that it shall not do, or cause to be done, any acts or things contesting or in any way impairing or tending to impair any portion of the right, title, and interest of Deep Idol or its licensors in and to such intellectual property rights.

             4.3 Nondisclosure and Use Restrictions. Each Party acknowledges that the Confidential Information constitutes valuable trade secrets and proprietary information of a Party, and each Party agrees that it shall use the Confidential Information of the other Party solely in accordance with the provisions of this Agreement and it will not disclose, or permit to be disclosed, the same directly or indirectly, to any third party without the other Party's prior written consent, except as otherwise permitted hereunder. Nothing in this Section 4.3 is intended to restrict or otherwise limit the exercise by a Party of the rights and licenses granted to it under this Agreement; provided that such Party uses reasonable measures to protect the confidentiality and value of the other Party's Confidential Information. Notwithstanding any provision of this Agreement, either Party may disclose this Agreement, in whole or in part (a) to its employees, officers, directors, attorneys, auditors, financial advisors and/or subcontractors who have a need to know and are legally bound to keep such information confidential by confidentiality obligations consistent with those of this Agreement; and (b) as reasonably deemed by a Party to be required by law (in which case each Party shall provide the other with prior written notification thereof, shall provide such Party with the opportunity to contest such disclosure, and shall use its reasonable efforts to minimize such disclosure to the extent permitted by applicable law). Each Party agrees to exercise due care in protecting the Confidential Information from unauthorized use and disclosure. In the event of actual or threatened breach of the provisions of this Section 4.3, the non-breaching Party will be entitled to seek immediate injunctive and other equitable relief, without waiving any other rights or remedies available to it. Each Party shall promptly notify the other in writing if it becomes aware of any violations of the confidentiality obligations set forth in this Agreement. Upon the termination of this Agreement, each receiving Party agrees to promptly return to disclosing Party or destroy all Confidential Information of the disclosing Party that is in the possession of receiving Party and to certify the return or destruction of all such Confidential Information and embodiments.

             5. REPRESENTATIONS, WARRANTIES AND EXCLUSIONS

             5.1 Representations and Warranties of Each Party. Each Party represents and warrants to the other Party that (a) such Party has the required power and authority to enter into this Agreement and to perform its obligations hereunder; (b) the execution of this Agreement and performance of its obligations thereunder do not and will not violate any other agreement to which it is a party; and (c) this Agreement constitutes a legal, valid, and binding obligation when signed by both Parties.

             5.2 Representations and Warranties of User. User further represents and warrants that User has the full legal authority to grant the rights in and to the User Created Content granted in this Agreement.

             5.3 Exclusions. EXCEPT AS EXPRESSLY SET FORTH HEREIN, THE DEEP IDOL PLATFORM IS PROVIDED ON AN "AS-IS" BASIS, AND DEEP IDOL DISCLAIMS ANY AND ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT, AND FITNESS FOR A PARTICULAR PURPOSE. USER ACKNOWLEDGES THAT DEEP IDOL DOES NOT WARRANT THAT THE DEEP IDOL PLATFORM WILL BE PROVIDED IN AN UNINTERRUPTED OR ERROR FREE FASHION AT ALL TIMES.

             5.4 Beta Stage. To the extent User receives a beta-stage version of the Deep Idol Platform, User agrees as follows until such time as the Deep Idol Platform is no longer a beta-stage version:

             User acknowledges and agrees that the Deep Idol Platform is still under development, may contain defects, deficiencies, errors, and omissions and is not at a level of functionality, performance, or compatibility of a commercial product offering. User shall be solely responsible for any data and/or software loss or corruption arising from any use of the Deep Idol Platform and for the protection and back-up of any User data and software used in conjunction with the Deep Idol Platform. Deep Idol reserves the right at any time unilaterally to abandon the Deep Idol Platform or, if it does include the Deep Idol Platform in a commercially released product, to alter features, licensing terms, or other characteristics of the commercial release. Deep Idol retains the right to modify or revise the Deep Idol Platform furnished to User hereunder.

             6. INDEMNIFICATION

             6.1 Infringement Defense. In the event of a claim brought against User arising from the infringement or misappropriation of a third party copyright, United States patent, trade secret, or trademark by reason of the use of the Deep Idol Platform (excluding any User Created Content incorporated therein) by User as permitted hereunder, Deep Idol shall, at its expense, defend such claim, and pay damages actually awarded or paid in connection therewith, including the reasonable fees and expenses of the attorneys engaged by Deep Idol for such defense, provided that (i) User shall promptly notify Deep Idol of such claim, (ii) Deep Idol shall have the sole and exclusive authority to defend and/or settle any such claim and (iii) User reasonably cooperates with Deep Idol in connection therewith.

             6.2 Actions in Response to Potential Infringement. If the use of the Deep Idol Platform by User has become, or in Deep Idol's opinion is likely to become, the subject of any claim of infringement, Deep Idol may at its option and expense (a) procure for User the right to continue using the Deep Idol Platform as set forth hereunder; (b) replace or modify the Deep Idol Platform to make it non-infringing so long as the Deep Idol Platform has at least equivalent functionality; (c) substitute an equivalent for the Deep Idol Platform or (d) if options (a)-(c) are not reasonably practicable, terminate this Agreement.

             6.3 Limitation on Infringement Indemnification. Deep Idol shall have no liability or obligation under Sections 6.1 and 6.2 with respect to any claim if such claim is caused in whole or in part by (a) compliance with designs, guidelines, plans, or specifications provided by User; (b) modification of the Deep Idol Platform by any party other than Deep Idol without Deep Idol' express consent; or (c) the combination, operation, or use of the Deep Idol Platform with other applications, portions of applications, product(s), data, or services where the Deep Idol Platform would not by itself be infringing. THIS SECTION 6 STATES DEEP IDOL'S ENTIRE AND EXCLUSIVE LIABILITY AND OBLIGATION, AND USER'S EXCLUSIVE REMEDY (AT LAW OR IN EQUITY), WHETHER STATUTORY, CONTRACTUAL, EXPRESS, IMPLIED, OR OTHERWISE, FOR ANY CLAIM OF ANY NATURE RELATED TO INFRINGEMENT OR MISAPPROPRIATION OF INTELLECTUAL PROPERTY.

             6.4 Indemnification by User. User shall indemnify, defend and hold harmless Deep Idol against any and all claims, damages, losses, liabilities, costs, and expenses (including reasonable attorney's fees) directly or indirectly brought against Deep Idol by any third party arising from (a) the use of the Deep Idol Platform in violation of the terms of this Agreement; (b) the exercise of any rights granted by User to Deep Idol in or to the User Created Content in accordance with this Agreement, or (c) for any of the circumstances described in Section 6.3; provided that: (i) Deep Idol shall promptly notify User of such claim, (ii) User shall have the sole and exclusive authority to defend and/or settle any such claim and (iii) Deep Idol reasonably cooperates with User in connection therewith.

             7. LIMITATION OF LIABILITY

             7.1 LIMITATIONS ON REMEDY. EXCEPT FOR LIABILITY ARISING FROM A BREACH BY USER OF SECTION 2, UNDER NO CIRCUMSTANCES AND UNDER NO LEGAL THEORY, WHETHER IN TORT, CONTRACT, OR OTHERWISE, SHALL EITHER PARTY BE LIABLE TO THE OTHER PARTY FOR ANY INDIRECT, SPECIAL, INCIDENTAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES OF ANY CHARACTER, INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF GOODWILL, LOST PROFITS, LOST SALES OR BUSINESS, WORK STOPPAGE, COMPUTER FAILURE OR MALFUNCTION, LOST DATA, OR FOR ANY AND ALL OTHER DAMAGES OR LOSSES, EVEN IF A REPRESENTATIVE OF A PARTY HAS BEEN ADVISED, KNEW, OR SHOULD HAVE KNOWN OF THE POSSIBILITY OF SUCH DAMAGES. EXCEPT FOR LIABILITY ARISING FROM A BREACH OF BY USER OF SECTION 2 OR A PARTY'S INDEMNIFICATION OBLIGATIONS SET FORTH IN SECTION 6, HEREOF, NEITHER PARTY SHALL BE LIABLE FOR ANY DIRECT DAMAGES, COSTS, OR LIABILITIES IN EXCESS OF THE AMOUNTS PAID OR PROPERLY PAYABLE BY USER DURING THE TWELVE MONTHS PRECEDING THE INCIDENT OR CLAIM. EXCEPT FOR BREACHES BY A USER OF SECTION 2, MONETARY DAMAGES, AS LIMITED BY THIS SECTION 7, WILL BE EACH PARTY'S SOLE AND EXCLUSIVE ALTERNATIVE REMEDY (AT LAW OR IN EQUITY) IN THE EVENT THAT ANY EXCLUSIVE REMEDY HEREUNDER IS FOUND TO FAIL ITS ESSENTIAL PURPOSE. THE PROVISIONS OF THIS SECTION 7 ALLOCATE THE RISKS UNDER THIS AGREEMENT BETWEEN THE PARTIES, AND THE PARTIES HAVE RELIED ON THE LIMITATIONS SET FORTH HEREIN IN DETERMINING WHETHER TO ENTER INTO THIS AGREEMENT.

             8. TERM, TERMINATION

             8.1 Term of Agreement. This Agreement will be effective from the Effective Date and continue until terminated in accordance with this Agreement (the "Term").

             8.2 Termination. Either Party may terminate this Agreement upon fifteen (15) days' prior written notice to the other Party. Either party may terminate this Agreement if the other party commits a material breach that is not cured within 30 days of written notice requiring remedy or, if the breach is the non-payment of money, that is not cured within 10 days of written notice.

             8.3 Obligations on Termination. Upon termination or expiration of the Term or other termination of this Agreement, all rights granted hereunder and all obligations of Deep Idol to provide the Deep Idol Platform shall immediately terminate. Termination of this Agreement or expiration of the Term shall not relieve User from paying all fees accruing prior to termination. Sections 1, 2.3, 2.4, 4, 6, 7, 8 and 9 shall survive the termination or expiration of this Agreement or the Term for any reason whatsoever.

             8.4 Force Majeure. No Party hereto shall have any liability under this Agreement for such Party's failure or delay in performing any of the obligations imposed by this Agreement to the extent such failure or delay is the result of any of the following events (each, a "Force Majeure Event"): (i) any fire, explosion, unusually severe weather, natural disaster, or Act of God; (ii) epidemic; any nuclear, biological, chemical, or similar attack; any other public health or safety emergency; any act of terrorism; and any action reasonably taken in response to any of the foregoing; (iii) any act of declared or undeclared war or of a public enemy, or any riot or insurrection; (iv) damage to machinery or equipment; any disruption in transportation, communications, electric power or other utilities, or other vital infrastructure; or any means of disrupting or damaging internet or other computer networks or facilities; (v) any strike, lockout, or other labor dispute or action; (vi) any action taken in response to any of the foregoing events by any civil or military authority; or (vii) any other event beyond such Party's control; provided that financial inability in and of itself shall not be a Force Majeure Event.

             9. GENERAL

             9.1 Publicity. Neither Party will make any separate public announcement regarding this Agreement or any of the contents contained herein without the prior written consent of the other Party, which will not be unreasonably withheld. Notwithstanding the foregoing, once user consents to the foregoing, during the Term, Deep Idol may (i) issue press releases announcing and/or describing the relationship between Deep Idol and User; (ii) use User's name and marks in any general listing of customers of Deep Idol in marketing and promotional materials, including on the Deep Idol website; (iii) use User's name in connection with proposals to third parties; and (iv) otherwise refer to User in print or electronic form for marketing, reference and other business purposes.

             9.2 No Assignment. Neither Party may assign this Agreement, or sublicense any of the rights granted herein, in whole or in part, without the prior written consent of the non-assigning Party, which consent may be withheld at the sole discretion of the non-assigning Party. Notwithstanding the foregoing, either Party may assign this Agreement without such consent to any person or entity controlling, controlled by, or controlled in conjunction with such Party or that acquires all or substantially all of the assets and business of the assigning Party to which this Agreement relates by merger or purchase, provided that such person or entity assumes in writing all of the terms and conditions of this Agreement. Any attempt by either Party to assign or transfer any of the rights, duties or obligations of this Agreement in violation of the foregoing shall be null and void.

             9.3 Amendment; Waiver. User may not amend or modify this Agreement, in whole or in part, except in a writing signed by a duly authorized representative of each Party. No provision or part of this Agreement or remedy hereunder may be waived except by a writing signed by a duly authorized representative of the Party making the waiver. Failure or delay by either Party to enforce any provision of this Agreement will not be deemed a waiver of future enforcement of that or any other provision.

             9.4 Relationship. Nothing in this Agreement shall be construed to place the Parties hereto in an agency, employment, franchise, joint venture, or partnership relationship. Neither Party will have the authority to obligate or bind the other in any manner, and nothing herein contained shall give rise or is intended to give rise to any rights of any kind to any third parties. Neither Party will represent to the contrary, either expressly, implicitly, or otherwise.

             9.5 Severability. In the event that any provision of this Agreement is found to be unenforceable, such provision will be reformed only to the extent necessary to make it enforceable, and such provision as so reformed will continue in effect, to the extent consistent with the intent of the Parties as of the Effective Date. If any provision or part of this Agreement will, to any extent, be or become invalid, illegal, or unenforceable, the remainder of this Agreement will continue in effect, and every other provision of this Agreement will remain valid and enforceable to the full extent permitted by applicable law. In such event, the invalid or unenforceable provision shall be reformed only to the extent necessary to make it enforceable, and such provision as so reformed will continue in effect, to the extent consistent with the intent of the Parties as of the Effective Date.

             9.6 Governing Law, Jurisdiction. All disputes, claims, or controversies arising out of this Agreement, or the negotiation, validity, or performance of this Agreement, or the transactions contemplated hereby shall be governed by and construed in accordance with the laws of the State of New York without regard to its rules of conflict of laws. Each of the Parties hereto hereby irrevocably and unconditionally consents to submit to the sole and exclusive jurisdiction of the courts of the State of New York and of the United States of America located in New York, New York (the "New York Courts") for any litigation among the Parties hereto arising out of or relating to this Agreement, or the negotiation, validity, or performance of this Agreement; waives any objection to the laying of venue of any such litigation in the New York Courts; and agrees not to plead or claim in any New York Court that such litigation brought therein has been brought in any inconvenient forum or that there are indispensable parties to such litigation that are not subject to the jurisdiction of the New York Courts.

             9.7 Notices. All notices under or related to this Agreement will be in writing and will reference this Agreement. Notices will be deemed given when: (i) delivered personally; (ii) sent by confirmed telecopy or other electronic means; (iii) three (3) days after having been sent by registered or certified mail, return receipt requested, postage prepaid; or (iv) one (1) day after deposit with a commercial overnight carrier, with written verification of receipt. All communications will be sent to the addresses set forth on the Cover Page or such other addresses, including email addresses, designated pursuant to this Section 9.7.

             9.8 Entire Agreement. This Agreement constitutes the entire agreement between the Parties. It supersedes and replaces all prior or contemporaneous understandings or agreements, written or oral, regarding such subject matter, and prevails over any conflicting terms or conditions contained on printed forms submitted with purchase orders, sales acknowledgments or quotations. This Agreement may not be modified or waived, in whole or part, except in writing and signed by an officer or duly authorized representative of both Parties.
             </p>
            </div>
        );
    }
}
