import React, {Component} from 'react';
import './Terms.css';

export default class Privacy extends Component {
    render() {
        return (
            <div className='scrollable'><p>
             Privacy Policy

             This Privacy Policy was last updated on March 11th, 2017.

             Our Policy
             Information We Collect
             Our Use of Your Personal Data and Other Information
             Our Disclosure of Your Personal Data and Other Information
             Your Choices
             Exclusions
             Children
             Links To Other Web Sites
             Security
             Other Terms and Conditions
             Changes to Deep Idol’s Privacy Policy
             Accessing Information; Contacting Deep Idol
             OUR POLICY:

             Welcome to the web site (the "Site") of Deep Idol, Inc. ("Deep Idol", "Amper, "we", "us" and/or "our"). This Site is operated by Deep Idol and has been created to provide information about our organization and to provide a platform for personal and professional music, audio, other media creation, etc. (the "Deep Idol Services") to our Site visitors ("you", "your"). This Privacy Policy sets forth Deep Idol's policy with respect to information including personally identifiable data ("Personal Data") and other information that is collected from Site visitors.

             INFORMATION WE COLLECT:

             When you interact with us through the Site, we may collect Personal Data and other information from you, as further described below:

             Personal Data That You Provide Through the Site: We collect Personal Data from you when you voluntarily provide such information, such as when you contact us with inquiries, respond to one of our surveys, register for access to the Deep Idol Services or use certain Deep Idol Services. Wherever Deep Idol collects Personal Data we make an effort to provide a link to this Privacy Policy.

             By voluntarily providing us with Personal Data, you are consenting to our use of it in accordance with this Privacy Policy. If you provide Personal Data to this Site, you acknowledge and agree that such Personal Data may be transferred from your current location to the offices and servers of Deep Idol and the authorized third parties referred to herein located in the United States.

             Other Information:

             Non-Identifiable Data: When you interact with Deep Idol through the Site, we receive and store certain personally non-identifiable information. Such information, which is collected passively using various technologies, cannot presently be used to specifically identify you. Deep Idol may store such information itself or such information may be included in databases owned and maintained by Deep Idol affiliates, agents or service providers. This Site may use such information and pool it with other information to track, for example, the total number of visitors to our Site, the number of visitors to each page of our Site, and the domain names of our visitors' Internet service providers. It is important to note that no Personal Data is available or used in this process.

             In operating this Site, we may use a technology called "cookies." A cookie is a piece of information that the computer that hosts our Site gives to your browser when you access the Site. Our cookies help provide additional functionality to the Site and help us analyze Site usage more accurately. For instance, our Site may set a cookie on your browser that allows you to access the Site without needing to remember and then enter a password more than once during a visit to the Site. On most web browsers, you will find a "help" section on the toolbar. Please refer to this section for information on how to receive notification when you are receiving a new cookie and how to turn cookies off. We recommend that you leave cookies turned on because they allow you to take advantage of some of the Site's features.

             This Site uses Mixpanel to help analyze how users use the site. The tool uses "cookies" to collect standard Internet log information and visitor behavior information. The information generated by the cookie about your use of the website (including IP address) is transmitted to Mixpanel. This information is then used to evaluate visitors' use of the website and to compile statistical reports on website activity for us. We further use the statistical analytics tool to track or to collect Personally Identifiable Information (PII) of visitors to our site including your account information and email address. We will use this information in order to maintain, enhance, or add to the functionality of the Website. Mixpanel will not share your PII or associate your PII with any other data held by Mixpanel.

             Aggregated Personal Data: In an ongoing effort to better understand and serve the users of the Deep Idol Services, Deep Idol often conducts research on its customer demographics, interests and behavior based on the Personal Data and other information provided to us. This research may be compiled and analyzed on an aggregate basis, and Deep Idol may share this aggregate data with its affiliates, agents and business partners. This aggregate information may or may not identify you personally. Deep Idol may also disclose aggregated user statistics in order to describe our services to current and prospective business partners, and to other third parties for other lawful purposes.

             OUR USE OF YOUR PERSONAL DATA AND OTHER INFORMATION:

             Deep Idol uses the Personal Data you provide in a manner that is consistent with this Privacy Policy. If you provide Personal Data for a certain reason, we may use the Personal Data in connection with the reason for which it was provided. For instance, if you contact us by e-mail, we will use the Personal Data you provide to answer your question or resolve your problem. Also, if you provide Personal Data in order to obtain access to the Deep Idol Services, we will use your Personal Data to provide you with access to such services and to monitor your use of such services. Deep Idol and its subsidiaries and affiliates (the "Deep Idol Related Companies") may also use your Personal Data, personally identifiable information, and other personally non-identifiable information collected through the Site to help us improve the content and functionality of the Site, to better understand our users and to improve the Deep Idol Services. Deep Idol and its affiliates may use this information to contact you in the future to tell you about services we believe will be of interest to you. If we do so, each communication we send you will contain instructions permitting you to "opt-out" of receiving future communications. In addition, if at any time you wish not to receive any future communications or you wish to have your name deleted from our mailing lists, please contact us as indicated below.

             If Deep Idol intends on using any Personal Data in any manner that is not consistent with this Privacy Policy, you will be informed of such anticipated use prior to or at the time at which the Personal Data is collected.

             OUR DISCLOSURE OF YOUR PERSONAL DATA AND OTHER INFORMATION:

             Deep Idol is not in the business of selling your information. We consider this information to be a vital part of our relationship with you. There are, however, certain circumstances in which we may share your Personal Data with certain third parties without further notice to you, as set forth below:

             Business Transfers: As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganization, dissolution or similar event, Personal Data may be part of the transferred assets.

             Related Companies: We may also share your Personal Data with our Related Companies for purposes consistent with this Privacy Policy.

             Agents, Consultants and Related Third Parties: Deep Idol, like many businesses, sometimes hires other companies to perform certain business-related functions. Examples of such functions include mailing information, maintaining databases and processing payments. When we employ another company to perform a function of this nature, we only provide them with the information that they need to perform their specific function.

             Legal Requirements: Deep Idol may disclose your Personal Data if required to do so by law or in the good faith belief that such action is necessary to (i) comply with a legal obligation, (ii) protect and defend the rights or property of Deep Idol, (iii) act in urgent circumstances to protect the personal safety of users of the Site or the public, or (iv) protect against legal liability.

             YOUR CHOICES:

             You can use the Site without providing any Personal Data. If you choose not to provide any Personal Data, you may not be able to use certain Deep Idol Services.

             EXCLUSIONS:

             This Privacy Policy does not apply to any Personal Data collected by Deep Idol other than Personal Data collected through the Site. This Privacy Policy shall not apply to any unsolicited information you provide to Deep Idol through this Site or through any other means. This includes, but is not limited to, information posted to any public areas of the Site, such as bulletin boards (collectively, "Public Areas"), any ideas for new products or modifications to existing products, and other unsolicited submissions (collectively, "Unsolicited Information"). All Unsolicited Information shall be deemed to be non-confidential and Deep Idol shall be free to reproduce, use, disclose, and distribute such Unsolicited Information to others without limitation or attribution.

             CHILDREN:

             Deep Idol does not knowingly collect Personal Data from children under the age of 13. If you are under the age of 13, please do not submit any Personal Data through the Site. We encourage parents and legal guardians to monitor their children's Internet usage and to help enforce our Privacy Policy by instructing their children never to provide Personal Data on this Site without their permission. If you have reason to believe that a child under the age of 13 has provided Personal Data to Deep Idol through this Site, please contact us, and we will endeavor to delete that information from our databases.

             1. Links to Other Web Sites:

             This Privacy Policy applies only to the Site. This Site may contain links to other web sites not operated or controlled by Deep Idol (the "Third Party Sites"). The policies and procedures we described here do not apply to the Third Party Sites. The links from this Site do not imply that Deep Idol endorses or has reviewed the Third Party Sites. We suggest contacting those sites directly for information on their privacy policies.

             2. Security:

             Deep Idol takes reasonable steps to protect the Personal Data provided via the Site from loss, misuse, and unauthorized access, disclosure, alteration, or destruction. However, no Internet or e-mail transmission is ever fully secure or error free. In particular, e-mail sent to or from this Site may not be secure. Therefore, you should take special care in deciding what information you send to us via e-mail. Please keep this in mind when disclosing any Personal Data to Deep Idol via the Internet.

             3. Other Terms and Conditions:

             Your access to and use of this Site is subject to the Terms of Use.

             4. Changes to Deep Idol's Privacy Policy:

             The Site and our business may change from time to time. As a result, at times it may be necessary for Deep Idol to make changes to this Privacy Policy. Deep Idol reserves the right to update or modify this Privacy Policy at any time and from time to time without prior notice. Please review this policy periodically, and especially before you provide any Personal Data. This Privacy Policy was last updated on the date indicated above. Your continued use of the Site after any changes or revisions to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.

             ACCESS TO INFORMATION; CONTACTING DEEP IDOL:

             To keep your Personal Data accurate, current, and complete, please contact us as specified below. We will take reasonable steps to update or correct Personal Data in our possession that you have previously submitted via this Site.

             Please also feel free to contact us if you have any questions about Deep Idol's Privacy Policy or the information practices of this Site.

             You may contact us as follows: Matthew Lewis, matthew@commonedits.com.

           </p> </div>
        );
    }
}
